"""
train_title_model.py — Train From-Scratch Transformer for Title Generation
==========================================================================
Trains the TitleTransformer (encoder-decoder) on (message, title) pairs
generated by generate_title_data.py.

Architecture:   Encoder-Decoder Transformer (Attention Is All You Need)
Tokenizer:      Word-level (built from training data)
Training:       Teacher forcing, cross-entropy loss, Adam + warmup
Output:         models/title_model/model.pt  (weights)
                models/title_model/vocab.json (tokenizer vocab)

Run:
    python scripts/train_title_model.py
"""

import json
import math
import random
import logging
from pathlib import Path

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

logging.basicConfig(level=logging.INFO, format="%(levelname)s | %(message)s")
logger = logging.getLogger(__name__)

BASE_DIR    = Path(__file__).parent.parent
DATA_FILE   = BASE_DIR / "data" / "training_data" / "title_pairs.jsonl"
MODEL_DIR   = BASE_DIR / "models" / "title_model"
MODEL_DIR.mkdir(parents=True, exist_ok=True)

# ── Hyperparameters ────────────────────────────────────────────────────────────
D_MODEL       = 64    # smaller model fits the dataset size better
N_HEADS       = 4
N_LAYERS      = 2     # shallower — less capacity to overfit
D_FF          = 128
DROPOUT       = 0.3
MAX_LEN       = 64
MAX_TITLE     = 12
BATCH_SIZE    = 64    # larger batches — smoother gradients
EPOCHS        = 80
LR            = 3e-4
WARMUP        = 300
CLIP_GRAD     = 0.5
LABEL_SMOOTH  = 0.1
WEIGHT_DECAY  = 1e-4
WORD_DROPOUT  = 0.15  # randomly mask 15% of source tokens during training
DEVICE        = torch.device("cuda" if torch.cuda.is_available() else "cpu")


# ── Import model ───────────────────────────────────────────────────────────────
import sys
sys.path.insert(0, str(BASE_DIR / "src"))
from title_model import TitleTransformer, WordTokenizer


# ── Dataset ────────────────────────────────────────────────────────────────────

class TitleDataset(Dataset):
    """Pairs of (tokenized_message, tokenized_title) tensors."""

    def __init__(self, pairs: list[dict], tokenizer: WordTokenizer,
                 augment: bool = False):
        self.tokenizer = tokenizer
        self.augment   = augment
        self.samples   = []

        for p in pairs:
            msg   = tokenizer.encode(p["message"], max_len=MAX_LEN)
            title = tokenizer.encode(p["title"],   max_len=MAX_TITLE)

            if len(msg) < 2 or len(title) < 2:
                continue

            tgt_in  = [tokenizer.BOS] + title
            tgt_out = title + [tokenizer.EOS]

            msg     = self._pad(msg,     MAX_LEN)
            tgt_in  = self._pad(tgt_in,  MAX_TITLE + 1)
            tgt_out = self._pad(tgt_out, MAX_TITLE + 1, pad_val=-100)

            self.samples.append((msg, tgt_in, tgt_out))

        logger.info(f"Dataset: {len(self.samples):,} samples")

    def _pad(self, seq: list[int], length: int, pad_val: int = 0) -> list[int]:
        seq = seq[:length]
        return seq + [pad_val] * (length - len(seq))

    def _word_dropout(self, ids: list[int]) -> list[int]:
        """Replace random non-padding tokens with [PAD].
        Always keeps at least 1 real token to prevent all-PAD → NaN attention."""
        real_indices = [i for i, tok in enumerate(ids) if tok != self.tokenizer.PAD]
        if not real_indices:
            return ids
        # Choose which real tokens to keep (at least 1 guaranteed)
        keep = {random.choice(real_indices)}   # always keep at least one
        result = list(ids)
        for i in real_indices:
            if i not in keep and random.random() < WORD_DROPOUT:
                result[i] = self.tokenizer.PAD
        return result

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        msg, tgt_in, tgt_out = self.samples[idx]
        if self.augment:
            msg = self._word_dropout(msg)
        return (
            torch.tensor(msg,     dtype=torch.long),
            torch.tensor(tgt_in,  dtype=torch.long),
            torch.tensor(tgt_out, dtype=torch.long),
        )


# ── LR Scheduler (Transformer warmup) ─────────────────────────────────────────

class WarmupScheduler:
    """Warmup then cosine decay — stable for small d_model."""

    def __init__(self, optimizer, warmup_steps: int, max_lr: float, total_steps: int):
        self.optimizer    = optimizer
        self.warmup_steps = warmup_steps
        self.max_lr       = max_lr
        self.total_steps  = total_steps
        self._step        = 0

    def step(self):
        self._step += 1
        s = self._step
        w = self.warmup_steps
        if s <= w:
            lr = self.max_lr * s / w          # linear warmup
        else:
            # cosine decay from max_lr to max_lr/10
            progress = (s - w) / max(1, self.total_steps - w)
            lr = self.max_lr * (0.1 + 0.9 * 0.5 * (1.0 + math.cos(math.pi * progress)))
        for group in self.optimizer.param_groups:
            group["lr"] = lr
        return lr


# ── Training loop ──────────────────────────────────────────────────────────────

def train():
    logger.info("=" * 60)
    logger.info("Title Transformer — Training")
    logger.info(f"Device: {DEVICE}")
    logger.info("=" * 60)

    # Load data
    if not DATA_FILE.exists():
        logger.error(f"Data file not found: {DATA_FILE}")
        logger.error("Run generate_title_data.py first.")
        return

    pairs = []
    for line in DATA_FILE.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line:
            try:
                pairs.append(json.loads(line))
            except Exception:
                pass

    logger.info(f"Loaded {len(pairs):,} training pairs")
    if len(pairs) < 50:
        logger.error("Too few pairs — run generate_title_data.py first.")
        return

    # Shuffle and split 90/10
    random.shuffle(pairs)
    split     = int(0.9 * len(pairs))
    train_p   = pairs[:split]
    val_p     = pairs[split:]

    # Build tokenizer from ALL pairs (so val tokens are known)
    tokenizer = WordTokenizer()
    tokenizer.build(
        [p["message"] for p in pairs] + [p["title"] for p in pairs],
        min_freq=2,
    )
    tokenizer.save(MODEL_DIR / "vocab.json")
    logger.info(f"Vocab size: {tokenizer.vocab_size:,}")

    # Datasets / loaders
    train_ds     = TitleDataset(train_p, tokenizer, augment=True)
    val_ds       = TitleDataset(val_p,   tokenizer, augment=False)
    train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True,  drop_last=True)
    val_loader   = DataLoader(val_ds,   batch_size=BATCH_SIZE, shuffle=False)

    # Model
    model = TitleTransformer(
        vocab_size = tokenizer.vocab_size,
        d_model    = D_MODEL,
        n_heads    = N_HEADS,
        n_layers   = N_LAYERS,
        d_ff       = D_FF,
        max_len    = MAX_LEN,
        dropout    = DROPOUT,
        pad_idx    = tokenizer.PAD,
    ).to(DEVICE)

    n_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    logger.info(f"Parameters: {n_params:,}")

    # Loss / optimizer
    total_steps = EPOCHS * len(train_loader)
    criterion = nn.CrossEntropyLoss(ignore_index=-100, label_smoothing=LABEL_SMOOTH)
    optimizer = torch.optim.Adam(model.parameters(), lr=LR, betas=(0.9, 0.98),
                                 eps=1e-9, weight_decay=WEIGHT_DECAY)
    scheduler = WarmupScheduler(optimizer, warmup_steps=WARMUP,
                                max_lr=LR, total_steps=total_steps)

    best_val_loss = float("inf")
    best_epoch    = 0

    for epoch in range(1, EPOCHS + 1):
        # ── Train ──────────────────────────────────────────────────────────────
        model.train()
        train_loss = 0.0

        for src, tgt_in, tgt_out in train_loader:
            src, tgt_in, tgt_out = src.to(DEVICE), tgt_in.to(DEVICE), tgt_out.to(DEVICE)

            logits = model(src, tgt_in)               # (B, T, V)
            B, T, V = logits.shape
            loss = criterion(
                logits.reshape(B * T, V),
                tgt_out.reshape(B * T),
            )

            optimizer.zero_grad()
            loss.backward()
            nn.utils.clip_grad_norm_(model.parameters(), CLIP_GRAD)
            optimizer.step()
            scheduler.step()

            train_loss += loss.item()

        train_loss /= len(train_loader)

        # ── Validate ───────────────────────────────────────────────────────────
        model.eval()
        val_loss = 0.0

        with torch.no_grad():
            for src, tgt_in, tgt_out in val_loader:
                src, tgt_in, tgt_out = src.to(DEVICE), tgt_in.to(DEVICE), tgt_out.to(DEVICE)
                logits = model(src, tgt_in)
                B, T, V = logits.shape
                loss = criterion(
                    logits.reshape(B * T, V),
                    tgt_out.reshape(B * T),
                )
                val_loss += loss.item()

        val_loss /= max(len(val_loader), 1)

        logger.info(
            f"Epoch {epoch:02d}/{EPOCHS}  "
            f"train_loss={train_loss:.4f}  val_loss={val_loss:.4f}"
        )

        # ── Sample generation every 5 epochs ──────────────────────────────────
        if epoch % 5 == 0:
            model.eval()
            sample_pairs = random.sample(val_p[:20], min(3, len(val_p)))
            for p in sample_pairs:
                tokens    = tokenizer.encode(p["message"], max_len=MAX_LEN)
                src_t     = torch.tensor([tokens], dtype=torch.long).to(DEVICE)
                generated = model.generate(
                    src_t,
                    bos_idx  = tokenizer.BOS,
                    eos_idx  = tokenizer.EOS,
                    max_steps = MAX_TITLE,
                )
                pred_title = tokenizer.decode(generated)
                logger.info(f"  msg:  {p['message'][:60]}")
                logger.info(f"  gold: {p['title']}")
                logger.info(f"  pred: {pred_title}")
                logger.info("")

        # ── Save best ──────────────────────────────────────────────────────────
        if val_loss < best_val_loss:
            best_val_loss = val_loss
            best_epoch    = epoch
            torch.save(model.state_dict(), MODEL_DIR / "model.pt")

    logger.info("=" * 60)
    logger.info(f"Training complete. Best val_loss={best_val_loss:.4f} at epoch {best_epoch}")
    logger.info(f"Model saved → {MODEL_DIR / 'model.pt'}")
    logger.info(f"Vocab saved → {MODEL_DIR / 'vocab.json'}")
    logger.info("")
    logger.info("Next step: the model is ready for use in src/title_generator.py")
    logger.info("=" * 60)


if __name__ == "__main__":
    train()
